import { useState } from 'react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { supabase } from '@/lib/backend';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { useCurrentBranchId } from '@/hooks/useBranchFilter';
import { Newspaper, BookOpen, Search, Plus, Sparkles, Clock, Tag, Loader2 } from 'lucide-react';

const categories = ['All', 'Crop Science', 'Livestock', 'Market Trends', 'Technology', 'Sustainability', 'Pest Control'];

const AgriNews = () => {
  const [activeCategory, setActiveCategory] = useState('All');
  const [searchQuery, setSearchQuery] = useState('');
  const [showCreate, setShowCreate] = useState(false);
  const [newArticle, setNewArticle] = useState({ title: '', content: '', category: 'general', tags: '' });
  const [aiPrompt, setAiPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const queryClient = useQueryClient();
  const branchId = useCurrentBranchId();

  const { data: articles = [], isLoading } = useQuery({
    queryKey: ['agri-articles', branchId],
    queryFn: async () => {
      let q = supabase.from('agri_articles').select('*').order('created_at', { ascending: false });
      if (branchId) q = q.or(`branch_id.eq.${branchId},branch_id.is.null`);
      const { data, error } = await q;
      if (error) throw error;
      return data;
    },
  });

  const createMutation = useMutation({
    mutationFn: async (article: typeof newArticle) => {
      const { error } = await supabase.from('agri_articles').insert({
        title: article.title,
        content: article.content,
        category: article.category,
        tags: article.tags.split(',').map(t => t.trim()).filter(Boolean),
        is_ai_generated: false,
        branch_id: branchId || null,
      });
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['agri-articles'] });
      toast.success('Article published!');
      setShowCreate(false);
      setNewArticle({ title: '', content: '', category: 'general', tags: '' });
    },
    onError: () => toast.error('Failed to create article'),
  });

  const generateAIArticle = async () => {
    if (!aiPrompt.trim()) return;
    setIsGenerating(true);
    try {
      const response = await supabase.functions.invoke('ai-generate-article', {
        body: { prompt: aiPrompt },
      });
      if (response.error) throw response.error;
      const data = response.data;
      setNewArticle({
        title: data.title || 'AI Generated Article',
        content: data.content || 'Content generation in progress...',
        category: data.category || 'general',
        tags: (data.tags || []).join(', '),
      });
      toast.success('Article generated by AI!');
    } catch {
      // Fallback: generate a sample article locally
      setNewArticle({
        title: `Agriculture Insights: ${aiPrompt}`,
        content: `This is an AI-generated article about "${aiPrompt}" in modern agriculture.\n\n## Key Points\n\n1. **Innovation**: Modern farming techniques are evolving rapidly with technology integration.\n2. **Sustainability**: Eco-friendly practices are becoming essential for long-term farm viability.\n3. **Market Trends**: Understanding global commodity markets helps farmers make informed decisions.\n\n## Detailed Analysis\n\nThe agricultural sector continues to adapt to changing climate conditions, market demands, and technological advancements. Farmers who embrace data-driven decision-making are seeing improved yields and reduced waste.\n\n## Recommendations\n\n- Stay updated with the latest research in your crop/livestock category\n- Consider precision agriculture tools for better resource management\n- Network with other farmers to share best practices`,
        category: 'general',
        tags: 'ai-generated, agriculture, farming',
      });
      toast.success('Sample article generated (connect AI backend for full generation)');
    } finally {
      setIsGenerating(false);
    }
  };

  const filtered = articles.filter(a => {
    const matchCat = activeCategory === 'All' || a.category.toLowerCase() === activeCategory.toLowerCase();
    const matchSearch = !searchQuery || a.title.toLowerCase().includes(searchQuery.toLowerCase()) || a.content.toLowerCase().includes(searchQuery.toLowerCase());
    return matchCat && matchSearch;
  });

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h1 className="text-3xl font-display font-bold">Agri News & Knowledge</h1>
            <p className="text-muted-foreground mt-1">Stay informed with the latest agricultural insights</p>
          </div>
          <Dialog open={showCreate} onOpenChange={setShowCreate}>
            <DialogTrigger asChild>
              <Button><Plus className="h-4 w-4 mr-2" /> New Article</Button>
            </DialogTrigger>
            <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle>Create Article</DialogTitle>
              </DialogHeader>
              <div className="space-y-4">
                {/* AI Generation */}
                <Card className="border-primary/20 bg-primary/5">
                  <CardContent className="p-4">
                    <div className="flex items-center gap-2 mb-2">
                      <Sparkles className="h-4 w-4 text-primary" />
                      <span className="font-medium text-sm">AI Content Generator</span>
                    </div>
                    <div className="flex gap-2">
                      <Input
                        placeholder="e.g., Best practices for maize farming in tropical climates"
                        value={aiPrompt}
                        onChange={e => setAiPrompt(e.target.value)}
                      />
                      <Button onClick={generateAIArticle} disabled={isGenerating} size="sm">
                        {isGenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Generate'}
                      </Button>
                    </div>
                  </CardContent>
                </Card>

                <Input placeholder="Article title" value={newArticle.title} onChange={e => setNewArticle(p => ({ ...p, title: e.target.value }))} />
                <select
                  className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                  value={newArticle.category}
                  onChange={e => setNewArticle(p => ({ ...p, category: e.target.value }))}
                >
                  {categories.filter(c => c !== 'All').map(c => (
                    <option key={c} value={c.toLowerCase()}>{c}</option>
                  ))}
                </select>
                <Textarea
                  placeholder="Article content (markdown supported)"
                  value={newArticle.content}
                  onChange={e => setNewArticle(p => ({ ...p, content: e.target.value }))}
                  rows={12}
                />
                <Input placeholder="Tags (comma separated)" value={newArticle.tags} onChange={e => setNewArticle(p => ({ ...p, tags: e.target.value }))} />
                <Button onClick={() => createMutation.mutate(newArticle)} disabled={!newArticle.title || !newArticle.content} className="w-full">
                  Publish Article
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        </div>

        {/* Search & Filter */}
        <div className="flex flex-col sm:flex-row gap-3">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input placeholder="Search articles..." value={searchQuery} onChange={e => setSearchQuery(e.target.value)} className="pl-9" />
          </div>
        </div>

        <div className="flex gap-2 flex-wrap">
          {categories.map(cat => (
            <Badge
              key={cat}
              variant={activeCategory === cat ? 'default' : 'outline'}
              className="cursor-pointer"
              onClick={() => setActiveCategory(cat)}
            >
              {cat}
            </Badge>
          ))}
        </div>

        <Tabs defaultValue="news">
          <TabsList>
            <TabsTrigger value="news"><Newspaper className="h-4 w-4 mr-1" /> News</TabsTrigger>
            <TabsTrigger value="knowledge"><BookOpen className="h-4 w-4 mr-1" /> Knowledge Base</TabsTrigger>
          </TabsList>

          <TabsContent value="news" className="space-y-4">
            {isLoading ? (
              <div className="flex items-center justify-center p-12">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
              </div>
            ) : filtered.length === 0 ? (
              <Card>
                <CardContent className="p-12 text-center">
                  <Newspaper className="h-12 w-12 mx-auto text-muted-foreground mb-3" />
                  <p className="text-muted-foreground">No articles yet. Create your first article or generate one with AI!</p>
                </CardContent>
              </Card>
            ) : (
              <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                {filtered.map(article => (
                  <Card key={article.id} className="hover:shadow-md transition-shadow cursor-pointer">
                    <CardHeader className="pb-2">
                      <div className="flex items-center justify-between">
                        <Badge variant="secondary" className="text-xs">{article.category}</Badge>
                        {article.is_ai_generated && (
                          <Badge variant="outline" className="text-xs"><Sparkles className="h-3 w-3 mr-1" /> AI</Badge>
                        )}
                      </div>
                      <CardTitle className="text-lg leading-tight mt-2">{article.title}</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm text-muted-foreground line-clamp-3">{article.content}</p>
                      <div className="flex items-center gap-3 mt-3 text-xs text-muted-foreground">
                        <div className="flex items-center gap-1">
                          <Clock className="h-3 w-3" />
                          {new Date(article.created_at).toLocaleDateString()}
                        </div>
                        {article.tags && article.tags.length > 0 && (
                          <div className="flex items-center gap-1">
                            <Tag className="h-3 w-3" />
                            {article.tags.slice(0, 2).join(', ')}
                          </div>
                        )}
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}
          </TabsContent>

          <TabsContent value="knowledge" className="space-y-4">
            <Card>
              <CardContent className="p-12 text-center">
                <BookOpen className="h-12 w-12 mx-auto text-muted-foreground mb-3" />
                <h3 className="text-lg font-semibold mb-2">Knowledge Base</h3>
                <p className="text-muted-foreground mb-4">Browse curated agricultural guides, best practices, and research summaries.</p>
                <Button variant="outline" onClick={() => setShowCreate(true)}>
                  <Sparkles className="h-4 w-4 mr-2" /> Generate Knowledge Article with AI
                </Button>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </DashboardLayout>
  );
};

export default AgriNews;
